credentials:
  usernames:
    victor:
      email: victor@aberration.com
      name: Victor
      password: $2b$12$.ejUPQtRJR9cLgZd.e7fUeBpUFf5gXT/9RwXsZNCKhvWuT96wsywK
    glenn:
      email: glenn@aberration.com
      name: Glenn
      password: $2b$12$93UbGSUEsFyVkbqOfXpCVengRlGyNsHChzy0SXY5w44Lc8YOHuSVi
    jimmy:
      email: jimmy@aberration.com
      name: Jimmy
      password: $2b$12$HZhqIM6ohDzMn1IeEUY20ufZlk4iLQyimhvn162.SQ.IXvFAwHwnm
    fred:
      email: fred@aberration.com
      name: Fred
      password: $2b$12$Pkr2C1L0Z3FNe1Vo5bebc.NV8inii7LklqV22IVlq1Z6c4e6z7EBO
cookie:
  expiry_days: 30
  key: thecode_signature_key # Must be string
  name: thecode_cookie_name
preauthorized:
  emails:
